---
- block:
  - name: install nginx
    apt: "name=nginx state=latest"
  - name: setup nginx cache dir
    file:
      path: "{{ nginx_cache_path }}"
      state: "directory"
      owner: "www-data"
      group: "www-data"
  - name: deploy nginx cache config
    template:
      src: "nginx_cache.conf.j2"
      dest: "/etc/nginx/conf.d/cache.conf"
      owner: "root"
      group: "root"
      mode: "0644"
    notify: restart nginx service
  tags:
    - nginx
