---
- block:
  - name: install nginx
    ansible.builtin.apt: "name=nginx state=latest"
  - name: setup nginx cache dir
    ansible.builtin.file:
      path: "{{ nginx_cache_path }}"
      state: "directory"
      owner: "www-data"
      group: "www-data"
  - name: deploy nginx proxy cache config
    ansible.builtin.template:
      src: "nginx_proxy_cache.conf.j2"
      dest: "/etc/nginx/conf.d/proxy_cache.conf"
      owner: "root"
      group: "root"
      mode: "0644"
    notify: restart nginx service
    when: nginx_proxy_cache_enabled
  - name: deploy nginx uwsgi cache config
    ansible.builtin.template:
      src: "nginx_uwsgi_cache.conf.j2"
      dest: "/etc/nginx/conf.d/uwsgi_cache.conf"
      owner: "root"
      group: "root"
      mode: "0644"
    notify: restart nginx service
    when: nginx_uwsgi_cache_enabled
  tags:
    - nginx
